name: book-api
services:

  nestjs:
    image: node:lts-alpine
    env_file:
      - .development.env
    ports:
      - "5000:5000"
    working_dir: /app
    command: 
      - sh
      - -c
      - |
        npm i
        npm run start:dev
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16-alpine
    env_file:
      - .development.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: